#ifndef _SOL_LOGICCONSTANTS_INCLUDED_
#define _SOL_LOGICCONSTANTS_INCLUDED_

enum sol_gameObjectTypes{
    GAME_OBJECT_VIRTUAL,
    GAME_OBJECT_STATIC_ANIMATION,
    GAME_OBJECT_STATIC_BITMAP,
    GAME_OBJECT_COUNT
};

#endif
