#ifndef _SOL_GRAPHICSCONSTANTSDEFINED_INCLUDED_
#define _SOL_GRAPHICSCONSTANTSDEFINED_INCLUDED_
#include <string>
using namespace std;

const string MEANINGLESS_STRING_CONSTANT = "ŒŽœ®¶Æ÷ÿþ";

enum sol_graphicsMessageTypes{
    GRAPHICS_MESSAGE_LOAD_BITMAP,
    GRAPHICS_MESSAGE_LOAD_ANIMATION,
    GRAPHICS_MESSAGE_LOAD_SPRITESHEET,
    GRAPHICS_MESSAGE_UNLOAD_BITMAP,
    GRAPHICS_MESSAGE_UNLOAD_ANIMATION,
    GRAPHICS_MESSAGE_UNLOAD_SPRITESHEET,
    GRAPHICS_MESSAGE_KILL_DEAD,
    GRAPHICS_MESSAGE_STOP,
    GRAPHICS_MESSAGE_TEST,
    GRAPHICS_MESSAGE_TYPE_COUNT
};

enum cacheMessageTypes{
    GRAPHICS_CACHE_MESSAGE_LOAD_BITMAP,
    GRAPHICS_CACHE_MESSAGE_LOAD_ANIMATION,
    GRAPHICS_CACHE_MESSAGE_LOAD_SPRITESHEET,
    GRAPHICS_CACHE_MESSAGE_TYPE_COUNT
};

enum sol_graphicsObjectTypes{
    GRAPHICS_OBJECT_ANIMATION,
    GRAPHICS_OBJECT_BITMAP,
    GRAPHICS_OBJECT_SPRITESHEET,
    GRAPHICS_OBJECT_TYPE_COUNT
};

#endif
